const courses = [
    {
        Id: 1,
        title: "Web Design Fundamentals",
        duration: "4 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the fundamentals of web design.",
        img: "../CoursesListPage/images/WebDesignFundamental.jpg",
    },
    {
        Id: 2,
        title: "UI/UX Design",
        duration: "6 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Master the art of creating user interfaces.",
        img: "../CoursesListPage/images/UI_UX_Design.png",
    },
    {
        Id: 3,
        title: "Mobile App Development",
        duration: "8 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Dive into the world of mobile app development.",
        img: "../CoursesListPage/images/MobileAppDevelopment.jpg",
    },
    {
        Id: 4,
        title: "Graphic Design for Beginners",
        duration: "10 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Discover the fundamentals of graphic design.",
        img: "../CoursesListPage/images/GraphicDesignforBeginners.png",
    },
    {
        Id: 5,
        title: "JavaScript Essentials",
        duration: "5 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the basics of JavaScript programming.",
        img: "../CoursesListPage/images/JavaScriptEssentials.jpg",
    },
    {
        Id: 6,
        title: "Advanced CSS Techniques",
        duration: "6 Weeks",
        level: "Advanced",
        lecturer: "John Doe",
        description: "Enhance your CSS skills.",
        img: "../CoursesListPage/images/AdvancedCSSTechniques.jpg",
    },

    {
        Id: 1,
        title: "Web Design Fundamentals",
        duration: "4 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the fundamentals of web design.",
        img: "../CoursesListPage/images/WebDesignFundamental.jpg",
    },
    {
        Id: 2,
        title: "UI/UX Design",
        duration: "6 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Master the art of creating user interfaces.",
        img: "../CoursesListPage/images/UI_UX_Design.png",
    },
    {
        Id: 3,
        title: "Mobile App Development",
        duration: "8 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Dive into the world of mobile app development.",
        img: "../CoursesListPage/images/MobileAppDevelopment.jpg",
    },
    {
        Id: 4,
        title: "Graphic Design for Beginners",
        duration: "10 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Discover the fundamentals of graphic design.",
        img: "../CoursesListPage/images/GraphicDesignforBeginners.png",
    },
    {
        Id: 5,
        title: "JavaScript Essentials",
        duration: "5 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the basics of JavaScript programming.",
        img: "../CoursesListPage/images/JavaScriptEssentials.jpg",
    },
    {
        Id: 6,
        title: "Advanced CSS Techniques",
        duration: "6 Weeks",
        level: "Advanced",
        lecturer: "John Doe",
        description: "Enhance your CSS skills.",
        img: "../CoursesListPage/images/AdvancedCSSTechniques.jpg",
    },

    {
        Id: 1,
        title: "Web Design Fundamentals",
        duration: "4 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the fundamentals of web design.",
        img: "../CoursesListPage/images/WebDesignFundamental.jpg",
    },
    {
        Id: 2,
        title: "UI/UX Design",
        duration: "6 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Master the art of creating user interfaces.",
        img: "../CoursesListPage/images/UI_UX_Design.png",
    },
    {
        Id: 3,
        title: "Mobile App Development",
        duration: "8 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Dive into the world of mobile app development.",
        img: "../CoursesListPage/images/MobileAppDevelopment.jpg",
    },
    {
        Id: 4,
        title: "Graphic Design for Beginners",
        duration: "10 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Discover the fundamentals of graphic design.",
        img: "../CoursesListPage/images/GraphicDesignforBeginners.png",
    },
    {
        Id: 5,
        title: "JavaScript Essentials",
        duration: "5 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the basics of JavaScript programming.",
        img: "../CoursesListPage/images/JavaScriptEssentials.jpg",
    },
    {
        Id: 6,
        title: "Advanced CSS Techniques",
        duration: "6 Weeks",
        level: "Advanced",
        lecturer: "John Doe",
        description: "Enhance your CSS skills.",
        img: "../CoursesListPage/images/AdvancedCSSTechniques.jpg",
    },

    {
        Id: 1,
        title: "Web Design Fundamentals",
        duration: "4 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the fundamentals of web design.",
        img: "../CoursesListPage/images/WebDesignFundamental.jpg",
    },
    {
        Id: 2,
        title: "UI/UX Design",
        duration: "6 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Master the art of creating user interfaces.",
        img: "../CoursesListPage/images/UI_UX_Design.png",
    },
    {
        Id: 3,
        title: "Mobile App Development",
        duration: "8 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Dive into the world of mobile app development.",
        img: "../CoursesListPage/images/MobileAppDevelopment.jpg",
    },
    {
        Id: 4,
        title: "Graphic Design for Beginners",
        duration: "10 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Discover the fundamentals of graphic design.",
        img: "../CoursesListPage/images/GraphicDesignforBeginners.png",
    },
    {
        Id: 5,
        title: "JavaScript Essentials",
        duration: "5 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the basics of JavaScript programming.",
        img: "../CoursesListPage/images/JavaScriptEssentials.jpg",
    },
    {
        Id: 6,
        title: "Advanced CSS Techniques",
        duration: "6 Weeks",
        level: "Advanced",
        lecturer: "John Doe",
        description: "Enhance your CSS skills.",
        img: "../CoursesListPage/images/AdvancedCSSTechniques.jpg",
    },

    {
        Id: 1,
        title: "Web Design Fundamentals",
        duration: "4 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the fundamentals of web design.",
        img: "../CoursesListPage/images/WebDesignFundamental.jpg",
    },
    {
        Id: 2,
        title: "UI/UX Design",
        duration: "6 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Master the art of creating user interfaces.",
        img: "../CoursesListPage/images/UI_UX_Design.png",
    },
    {
        Id: 3,
        title: "Mobile App Development",
        duration: "8 Weeks",
        level: "Intermediate",
        lecturer: "John Doe",
        description: "Dive into the world of mobile app development.",
        img: "../CoursesListPage/images/MobileAppDevelopment.jpg",
    },
    {
        Id: 4,
        title: "Graphic Design for Beginners",
        duration: "10 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Discover the fundamentals of graphic design.",
        img: "../CoursesListPage/images/GraphicDesignforBeginners.png",
    },
    {
        Id: 5,
        title: "JavaScript Essentials",
        duration: "5 Weeks",
        level: "Beginner",
        lecturer: "John Doe",
        description: "Learn the basics of JavaScript programming.",
        img: "../CoursesListPage/images/JavaScriptEssentials.jpg",
    },
    {
        Id: 6,
        title: "Advanced CSS Techniques",
        duration: "6 Weeks",
        level: "Advanced",
        lecturer: "John Doe",
        description: "Enhance your CSS skills.",
        img: "../CoursesListPage/images/AdvancedCSSTechniques.jpg",
    },
];

window.courses = courses;
